mystorms <- read_tsv("data_storms.tsv")

# Make a table of how many days per month had a category 3+ storm before 1990
mystorms %>%
  filter(year < 1990, category >= 3) %>%
  group_by(month) %>%
  summarise(`Days.of.3+.Storms.Before.1990`=n()/4)

# Make a table of how many days per month had a category 3+ storm during and after 1990
mystorms %>%
  filter(year >= 1990, category >= 3) %>%
  group_by(month) %>%
  summarise(`Days.of.3+.Storms.After.1990`=n()/4)

# From the storms dataset in dplyr (dplyr::storms) give the median pressure and the range
#   of pressures for each year
mystorms %>%
  group_by(year) %>%
  summarise(median_pressure = median(pressure),
            delta_pressure = max(pressure) - min(pressure))

# Give the mean and median pressure by year and name for only hurricanes
mystorms %>%
  group_by(year,name) %>%
  filter(status == "hurricane") %>%
  summarise(mean.pressure = mean(pressure),
            median.pressure = median(pressure))

# Generate a tibble for each of the following: year, status counting each unique name
mystorms %>%
  group_by(year,status) %>%
  summarise(unique_storms = n_distinct(name))

# Give the number of category 4+ storms that have happened each year and 
#  the average month per year that a category 4+ hurricane has happened
#    Take into account the days and hours of the of the month when accounting for 
#    the mean month of the storms.
month.to.days <-
  function (x){
    days_in_month = list(
      "1" = 31,
      "2" = 28,
      "3" = 31,
      "4" = 30,
      "5" = 31,
      "6" = 30,
      "7" = 31,
      "8" = 31,
      "9" = 30,
      "10" = 31,
      "11" = 30,
      "12" = 31)
    ret_val <- days_in_month[x]
    return(unlist(ret_val))
  }
mystorms %>%
  group_by(year) %>%
  filter(category >= 4) %>%
  summarise(storm.count = n_distinct(name),
            mean_month = mean(month+day/month.to.days(month)+hour/24))
